# Generated by Django 3.2.6 on 2021-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], default='ERKAK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('imdb', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('actors', models.ManyToManyField(to='myapp.Actor')),
            ],
        ),
    ]
